### ISSUE TITLE
大佬看下limit_execution: "* 0 * * *"参数，用了后时间就对不上了

### ISSUE THREAD

**Issue by Pa55w0rd** [anjia0532/elastalert-docker#13]
大佬看下limit_execution: "* 0 * * *"参数，用了后时间就对不上了

**Comment by Pa55w0rd** [comment]
现象：定义每天0点开启规则，触发规则的时间-8，告警时间+8，没有一个时间点正确的

**Comment by Pa55w0rd** [comment]
举例：每天0点运行规则，前24小时内，name唯一值大于100告警，当前时间为2022年5月18日0点，结果查询时间为2022年5月16日16点 - 2022年5月17日16点，不是2022年5月17日0-24点，告警时间正常在18日0点左右告警，结果在18日的8点告警的

**Comment by Pa55w0rd** [comment]
不添加limit_execution: ，结果都是正常的，说明时区是没有问题的

**Comment by anjia0532** [comment]
你用的 elastalert2?

**Comment by anjia0532** [comment]
我这个库给 elastalert 用的

**Comment by anjia0532** [comment]
你的环境(ES版本,ElastAlert还是ElastAlert2, 用的哪个版本,运行的配置,改没改默认时区,开没开Time增强),嘛都不说,没法给你分析啊

**Comment by Pa55w0rd** [comment]
> 你的环境(ES版本,ElastAlert还是ElastAlert2, 用的哪个版本,运行的配置,改没改默认时区,开没开Time增强),嘛都不说,没法给你分析啊

我对es不是很熟悉，我是用的elastalert，用的是你的docker起的，es版本7.17.3 ，也是docker起的，时区通过都是上海，time增强我也不清楚

**Comment by Pa55w0rd** [comment]
日志存入elk都转化成了0时区的

**Comment by anjia0532** [comment]
ElastAlert 的 limit_execution 逻辑代码

https://github.com/Yelp/elastalert/blob/1dc4f30f30d39a689f419ce19c7e2e4d67a50be3/elastalert/elastalert.py#L1256-L1260

你的Rules,Docker 启动命令或者 Docker-Compose.yml  去掉敏感参数(真实地址,密码啥的) 贴一下.

报警截图(如果有敏感数据,打码) 贴一下

**Comment by Pa55w0rd** [comment]
写入es的日志
```json
{
      "candidateid" => "xxx",
       "@timestamp" => 2022-05-17T05:32:48.000Z,
              "url" => "https://xxx",
       "event_type" => "candidate_download",
         "@version" => "1",
               "ip" => "x.x.x.x",
         "deptName" => "xx",
          "browser" => "Chrome 101.0.4951.67",
        "timestamp" => "2022-05-17 13:32:48 +0800",
    "candidateinfo" => "xx",
         "userName" => "Rxed Waxngxxx",
     "ctsCookiesId" => "",
    "event_type_cn" => "下载事件",
        "ci_number" => "xxx",
         "location" => "xxx"
}
```
起docker的命令
```sh
docker run -e"ELASTICSEARCH_HOST=es-host" \
    -e"CONTAINER_TIMEZONE=Asia/Shanghai"  \
    -e"TZ=Asia/Shanghai" \
    -e"ELASTALERT_DINGTALK_ACCESS_TOKEN=xxx" \
    -e"ELASTALERT_DINGTALK_SECURITY_TYPE=sign" \
    -e"ELASTALERT_DINGTALK_SECRET=xxx" \
    anjia0532/elastalert-docker:v0.2.4
```

rule规则
```yaml
name: test
type: cardinality
index: elk_userlog_*
cardinality_field: candidateid
max_cardinality: 10
ignore_null: true 
query_key: ci_number
limit_execution: "0 0 * * *"
# INFO:elastalert:Pausing test until next run at 2022-05-21 08:00 CST

buffer_time:
  hours: 10
timeframe:
  hours: 10
filter:
- query:
    query_string:
      query: "event_type: candidate_download"

# 告警抑制
# 5 分钟内相同的报警不会重复发送
realert:
  minutes: 5

exponential_realert:
# 指数级扩大 realert 时间，中间如果有报警，
# 则按照 5 -> 10 -> 20 -> 40 -> 60 不断增大报警时间到制定的最大时间，
# 如果之后报警减少，则会慢慢恢复原始 realert 时间
exponential_realert:
  hours: 1

alert:
- "elastalert_modules.dingtalk_alert.DingTalkAlerter"
#- "elastalert_modules.wechat_qiye_alert.WeChatAlerter"

match_enhancements:
- "elastalert_enhancements.TimeEnhancement.TimeEnhancement"

dingtalk_at_all: true
dingtalk_msgtype: markdown

alert_text: "
 ### 通知:规则《22:00-次日8:00，下载次数大于10次》
 - **登录用户:**{}\n
 - **姓名:**{}\n
 - **部门:**{}\n
 - **登录IP地址:**{}\n
 - **事件:**{}\n
 - **时间:**{}\n
 - **详情:** ```当前用户在非工作时间内，下载次数大于10次，请确认是否正常```
 "

alert_text_type: alert_text_only

alert_text_args:
 - ci_number
 - userName
 - deptName
 - ip
 - event_type
 - local_time

```
配置了limit_execution: "0 0 * * *"，每天早上8点报警 ，18日早上8点的告警
```
通知:规则《22:00-次日8:00，下载次数大于10次》 
登录用户:xxxx
姓名:xxx
部门:xxx
登录IP地址:xxx
事件:candidate_download
时间:2022-05-17 13:32 CST
详情: 当前用户在非工作时间内，下载次数大于10次，请确认是否正常
```
